name = "game-fetcher"
main = "./src/index.ts"
compatibility_date = "2023-05-11"

# used to turn off setting up of *.workers.dev subdomain since
# since this is only a scheduled worker
workers_dev = false

[vars]
GAMES_URL = "http://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard"
LOGGER_URL = "https://logs-prod-us-central2.grafana.net/loki/api/v1/push"
LOGGER_USER = "477117"

[triggers]
crons = [ "0 * * * *" ]

[env.staging]
kv_namespaces = [
  { binding = "DB", id = "0af4885463454e4abe264658308e90cf" }
]
GAMES_URL = "http://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard"
LOGGER_URL = "https://logs-prod-us-central2.grafana.net/loki/api/v1/push"
LOGGER_USER = "477117"

[env.production]
kv_namespaces = [
  { binding = "DB", id = "3bec0009978745ef876f8fbcf6f1797f" }
]
[env.production.vars]
GAMES_URL = "http://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard"
LOGGER_URL = "https://logs-prod-us-central2.grafana.net/loki/api/v1/push"
LOGGER_USER = "477117"


