name = "lockrace-game-fetcher"
main = "src/index.ts"
compatibility_date = "2023-05-11"
workers_dev = false

kv_namespaces = [
  { binding = "DB", id = "3bec0009978745ef876f8fbcf6f1797f", preview_id = "0af4885463454e4abe264658308e90cf" }
]

[triggers]
crons = [ "0 * * * *" ]

[vars]
GAMES_URL = "http://site.api.espn.com/apis/site/v2/sports/baseball/mlb/scoreboard"
LOKI_URL = "https://logs-prod-us-central2.grafana.net/loki/api/v1/push"
LOKI_USER = "477117"
